name: 'Run Komac'
description: 'Sets up and runs Komac with optional customizations'
branding:
  color: 'blue'
  icon: 'upload-cloud'

inputs:
  komac-version:
    description: 'Komac version to use (default: latest)'
    required: false
    default: 'latest'
  args:
    description: 'Arguments to run Komac with'
    required: true
  custom-fork-owner:
    description: 'Specify a custom fork owner of Komac, if any'
    required: false
  custom-tool:
    description: 'Name of a custom tool to use with Komac'
    required: false
  custom-tool-url:
    description: 'URL of the custom tool, if applicable'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Check and Install OpenSSL
      shell: bash
      run: |
        if ! openssl version; then
          echo "OpenSSL is not installed. Installing..."
          sudo apt-get update
          sudo apt-get install openssl -y
        else
          echo "OpenSSL is already installed."
        fi

    - name: Check for Komac Installation
      id: check_komac
      shell: bash
      run: |
        if komac --version &> /dev/null; then
          echo "Komac is already installed."
          echo "komac_installed=true" >> $GITHUB_OUTPUT
        else
          echo "Komac is not installed."
          echo "komac_installed=false" >> $GITHUB_OUTPUT
        fi

    - name: Install Komac
      if: steps.check_komac.outputs.komac_installed == 'false'
      shell: bash
      run: |
        version=${{ inputs.komac-version }}
        if [ "$version" = "latest" ]; then
          version=$(wget -qO- https://api.github.com/repos/russellbanks/Komac/releases/latest | grep 'tag_name' | cut -d'"' -f4 | sed 's/v//')
        fi
        wget https://github.com/russellbanks/Komac/releases/download/v$version/KomacPortable-linux-x64.tar.gz -O komac.tar.gz
        tar -xzf komac.tar.gz && rm komac.tar.gz
        mkdir -p $HOME/.local/bin
        mv KomacPortable-linux-x64 $HOME/.local/bin/komac
        chmod +x $HOME/.local/bin/komac
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Set Custom Environment Variables
      shell: bash
      run: |
        if [[ -n "${{ inputs.custom-fork-owner }}" ]]; then
          echo "KOMAC_FORK_OWNER=${{ inputs.custom-fork-owner }}" >> $GITHUB_ENV
        fi
        if [[ -n "${{ inputs.custom-tool }}" ]]; then
          echo "KOMAC_CREATED_WITH=${{ inputs.custom-tool }}" >> $GITHUB_ENV
        fi
        if [[ -n "${{ inputs.custom-tool-url }}" ]]; then
          echo "KOMAC_CREATED_WITH_URL=${{ inputs.custom-tool-url }}" >> $GITHUB_ENV
        fi

    - name: Run Komac
      shell: bash
      run: $HOME/.local/bin/komac ${{ inputs.args }}
