name: Test Action
on: [push]

jobs:
  test:
    name: Print Komac Version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Komac
      uses: ./
      with:
        args: '--version'
