name: Test Action
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Get latest commit hash
      id: latest_sha
      run: echo "::set-output name=sha::$(git rev-parse HEAD)"
    - run: echo "Latest commit hash is ${{ steps.latest_sha.outputs.sha }}"
    - name: Run Komac
      uses: michidk/run-komac@2007915c9ec851290e3301f3ea465b882b19ffa4
      with:
        args: '--version'
